### ISSUE TITLE
I have a problem with the installation

### ISSUE THREAD

**Issue by mariuszmalek** [CympleTech/ESSE#17]
<img width="1014" alt="Zrzut ekranu 2022-02-26 o 14 04 13" src="https://user-images.githubusercontent.com/26696860/155844393-237f368a-c82d-4a15-953d-2ae0464bdb39.png">

**Comment by sunhuachuang** [comment]
Yes, I also got this error, but when I debug, I found that `quinn` still has this function, emm...

So, in `main` branch, I locked quinn version
`quinn = { version = "=0.8.0", features = ["tls-rustls"], default-features = false }`

Do you want to use git path instead of crates ? If need crates, I will publish a patch version to fix it.

**Comment by sunhuachuang** [comment]
BTW, ESSE is refactoring a big breaking change. Maybe you can waiting some time to compile from source.

**Comment by mariuszmalek** [comment]
So why am I still having this error? Every time I download ESSE and run "cargo build --release" I get this error. A few days ago it works normally but when I run "cargo update" it's a crack (I'm new to rust).

Even tried to download chamomile and dump it into the core folder to not download from the repository but this leads to new bugs: /

**Comment by mariuszmalek** [comment]
I will be grateful for any help. Regarding just waiting for the full version of ESSE, so far I'm only learning Rust and Flutter from your code.

**Comment by sunhuachuang** [comment]
> Even tried to download chamomile and dump it into the core folder to not download from the repository but this leads to new bugs

I can guess your error, because when you download and deps local crates, but others also deps that will break. `tdn` also deps on it. So the best way is add `chamomile` to patch of crates in `Cargo.toml`
```
# DEBUG patch.
[patch.crates-io]
chamomile = { git = "https://github.com/cympletech/chamomile" }
chamomile_types = { git = "https://github.com/cympletech/chamomile" }
tdn = { git = "https://github.com/cympletech/tdn" }
tdn_types = { git = "https://github.com/cympletech/tdn" }
tdn_did = { git = "https://github.com/cympletech/tdn" }
```
Source is here: https://github.com/CympleTech/ESSE/blob/dev/Cargo.toml#L69

And if you don't care many comments on `dev` branch, you can also compile this branch.

**Comment by sunhuachuang** [comment]
And if you need more instant messaging, you can join our discord, I'm always there. https://discord.gg/UfFjp6Kaj4

**Comment by sunhuachuang** [comment]
I think it is ready to close, if any others, please let me know.
